name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest
      options: --user root
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build APK
        run: |
          yes | buildozer android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: 5MConcrete-APK
          path: bin/*.apk
